name: CI - Build Qt for Apple Silicon

on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

  release:
    types: [published]
permissions: write-all
jobs:
  build:
    name: Build Qt for Apple Silicon
    runs-on: macos-26
    
    if: github.repository_owner == 'pyquick'

    env:
      # GitHub Information
      branch: ${{ github.ref }}
      tag: ${{github.env.tag_name}}
      commiturl: ${{ github.event.head_commit.url }}${{ github.event.release.html_url }}
      commitdate: ${{ github.event.head_commit.timestamp }}${{ github.event.release.published_at }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          rm -rf Univ*
          rm -rf *pay*.dmg
          /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 -m pip install -r requirements_macOS.txt
      
      - name: Free up space
        run: |
          mkdir empty_dir
          rsync -a --delete empty_dir/ /Applications/Xcode_16.1_beta.app/
          rsync -a --delete empty_dir/ /Applications/Xcode_16_beta_6.app/
          rsync -a --delete empty_dir/ /Applications/Xcode_15.3.app/
          rsync -a --delete empty_dir/ /Applications/Xcode_15.2.app/
          rsync -a --delete empty_dir/ /Applications/Xcode_15.1.app/
          rsync -a --delete empty_dir/ /Applications/Xcode_15.0.1.app/
          rsync -a --delete empty_dir/ /Applications/Xcode_14.3.1.app/
          rsync -a --delete empty_dir/ /Users/runner/Library/Android/sdk/
          df -h

      - name: Force Universal charset for Python
        run: |
          /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 -m pip uninstall -y charset_normalizer
          /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 -m pip install https://dl.espressif.cn/pypi/charset-normalizer/charset_normalizer-3.4.7-cp312-cp312-macosx_10_13_universal2.whl

      - name: Prepare Assets (--prepare-assets)

        run: >
          /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 Build-Project.command
          --run-as-individual-steps
          --prepare-assets

      - name: Prepare Application (--prepare-application)
        run: >
          /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 Build-Project.command
          --git-branch "${{ env.branch }}" --git-commit-url "${{ env.commiturl }}" --git-commit-date "${{ env.commitdate }}"
          --reset-pyinstaller-cache
          --run-as-individual-steps
          --prepare-application

      - name: Prepare Package (--prepare-package)
        run: >
          /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 Build-Project.command
          --run-as-individual-steps
          --prepare-package
     

      - name: Upload Installation Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacBoxTool-arm64.pkg
          path: ./dist/MacBoxTool-arm64.pkg

      - name: Upload Uninstaller Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacBoxTool-Uninstaller-arm64.pkg
          path: ./dist/MacBoxTool-Uninstaller-arm64.pkg

      - name: Create Release on Push
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.tag}}
          name: ${{env.tag}}
          prerelease: false
          files: |

            ./dist/MacBoxTool-arm64.pkg
            ./dist/MacBoxTool-Uninstaller-arm64.pkg